@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bonker.swordinthestone.common.block.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;