@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bonker.swordinthestone.client.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;