@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bonker.swordinthestone.server.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;