@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bonker.swordinthestone.common.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;