@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bonker.swordinthestone.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;