@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bonker.swordinthestone.common.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;